name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.0', '8.1', '8.2' ]
    name: PHP ${{ matrix.php }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, gd, zip
          tools: composer, phpstan, phpcs

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Ensure PHPUnit is executable
        run: chmod +x vendor/bin/phpunit

      - name: Run PHPUnit
        run: vendor/bin/phpunit --testdox

      - name: Ensure PHPStan is executable
        run: chmod +x vendor/bin/phpstan

      - name: Run PHPStan (max level)
        run: vendor/bin/phpstan analyse --level=max .

      - name: Run PHPCS (WordPress Coding Standards)
        run: |
          vendor/bin/phpcs --standard=WordPress --ignore=vendor .
